### ISSUE TITLE
Comparison weather data between AC-Orsbach and EBC-station

### ISSUE THREAD

**Issue by Jun-Jiang-92** [RWTH-EBC/AixWeather#27]
**Describe the bug**
I compared the data from both weather stations under the same date and time. There are a lot of differences, including:

Regarding the values from the EBC weather station:

- If no data available, it uses a default value (e.g. 20 °C for ambient dry bulb temperature and 50 % for the r.h.), instead interpolating the value.
- The solar radiation values (HDirNor, HDifNor and HGloHor) are all too high. Some values of HDirNor in Feburary 2023 are almost 1000 W/m² and nearly approaches the solar constant . There should be some bugs here.

Regarding the values from the AC-Orsbach:

- No values in winSpe and winDir

**To Reproduce**
Download both data in *.mos format and import with AixLib package "AixLib.BoundaryConditions.WeatherData.ReaderTMY3". Then, run the simulation.

**Expected behavior**
The data are (almost) consistent with each other.

**Screenshots**
![grafik](https://github.com/RWTH-EBC/AixWeather/assets/59657205/1c81fc6a-b688-49d4-a986-828f69c216ea)

**Additional context**
None

**Bug Fix Suggestion**
There should be some bugs by the convertion and data export.

**Comment by MartinRaetz** [comment]
Thank you @Jun-Jiang-92.

I see three probable causes:

1. There is a bug inside the tool when converting the radiation values
2. The measurements at EBC are not what they seem to be (e.g. "diffuse-radiation" is this really the diffuse radiation for the whole sky or just the radiation hitting the sensor when blocking direct sunlight?)
3. The measurements at EBC are faulty.

The interpolation with default values is currently the desired behavior, as regular interpolation does not seem much more accurate to me and I think that it is valuable to see easily when data is missing. You may argue your point of view and we can think about changing it. 

I would appreciate if you could have a look at this. The first and most helpful thing would be finding out the exact meaning of the EBC measurements and documenting them here. Then we can check the code together, whether its correctly handled.

**Comment by Jun-Jiang-92** [comment]
@MartinRaetz I got some updates.

Regarding the EBC weather station:

- There are some data sheets from the manufactor here: W:\EBC_Intern\Messtechnik\Wetterstation\Thies. The global and diffuse radiations are measured with pyranometer in W/m².
- Compared with the data from aedifion, both parameters "HDifHor" and "HGloHor" in the simulation data are same as the data "global-radiation" and "diffuse-radiation" from the weather station.
![grafik](https://github.com/RWTH-EBC/AixWeather/assets/59657205/93787e9d-81bc-4dc9-a305-e6b2a4752e01)
I noticed that, in the generated .mos data, radiations are described with the unit of "Wh/m²". And in the simulation, parameters are denoted with the unit "W/m²". I am not sure about, which kind of input does Modelica need for the simulation from the weather data and how the modelica converts the data internally. It would be better that we have a discussion about that.

Regarding the missing values of AC Orsbach:

You are right. There is not any values available under https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/wind/historical/, since for all of the weather stations, the historical value is only availabel to the end of 2022 or even earlier. So it means, it is not possible to achieve a complete weather data set for any of "this" year. Is that right?

Does the old weather tool have the same problem? I also checked other directories but not found if there is somewhere the wind data of last months are saved.

**Comment by MartinRaetz** [comment]
@Jun-Jiang-92 Thank you for that deep dive!

I think 
This is what the Tool currently expects the ERC data to be:
```
'4121.weatherstation.diffuse-radiation': {'core_name': 'DiffHorRad', 'time_of_meas_shift': 'foll2ind', 'unit': "Wh/m2"},
'4121.weatherstation.global-radiation': {'core_name': 'GlobHorRad', 'time_of_meas_shift': 'foll2ind', 'unit': "Wh/m2"}
```
Unit seems to be correct as we have hourly measurements.
The data point need clarification: AixWeather expects both radiations to be only the horizontal radiations. Can you verify that the ERC measures this?

Regarding your second point "Aedifion vs. Simulation", I need clarification. Did not understand that. 

Regarding the completeness of weather data: You may only pull what is available online, regardless the Tool. Old and new version use the same data origin.

**Comment by Jun-Jiang-92** [comment]
@MartinRaetz The EBC weather station should measure the global horizontal irradiance (GHI) and the diffuse horizontal irradiance (DHI).

As described in the following links:
https://www.hukseflux.com/applications/solar-energy-pv-system-performance-monitoring/what-is-a-pyranometer
https://www.yellowhaze.in/solar-irradiance/
https://en.wikipedia.org/wiki/Solar_irradiance
If the pyramometer is horizontally aligned, as on the EBC weather station, it measures the global horizontal inradiance (GHI). The GHI has a range from 0 to 1400 W/m², by which the maximum is the solar constant. Ist that the exact parameter to be converted into the 'GloHorRad'?

For the comparison between Aedifion and .mos data, is the data flow now '4121.weatherstation.diffuse-radiation' -> 'DiffHorRad' -> 'HDifHor' without any conversions in the process? As results, the values in the simulation are the same as in the aedifion now. Is that true?

Now, I'm checking the conversion from DWD into the .mos data. Does the tool use "DS_10" and "GS_10" as data source now?
https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/solar/BESCHREIBUNG_obsgermany_climate_10min_solar_de.pdf
Could you show me how the conversion works for the data processing from DWD to .mos?

**Comment by MartinRaetz** [comment]
Hey @Jun-Jiang-92, thank you for checking and clarifying!

Perfect! In that case, the conversion of the ERC radiation is correct, as the measured value is the desired value.

And yes, DS_10 and GS_10, you find the data conversion dictionary for the DWD data here: 
aixweather/transformation_to_core_data/DWD.py:15

Can you, for one time step, calculate the DWD horizontal radiations and compare them with the radiations given by the Tool?

**Comment by MartinRaetz** [comment]
```
      15000;202301091000;    3;   5.4;   5.4;   0.000;-999;eor
      15000;202301091010;    3;   3.3;   3.3;   0.000;-999;eor
      15000;202301091020;    3;   2.1;   2.1;   0.000;-999;eor
      15000;202301091030;    3;   2.9;   2.9;   0.000;-999;eor
      15000;202301091040;    3;   3.2;   3.2;   0.000;-999;eor
      15000;202301091050;    3;   2.5;   2.5;   0.000;-999;eor
```
This is the raw DWD data, summing up the DiffHorRad for one hour (third column) results in 19.4 J/cm2.
Which is divided by 3600 (Joule to Wh) and multiplied by 10000 (cm2 to m2), resulting in 53,88 Wh/m2.

As far as I can see, this is the value that the tool also provides. Please verify the correctness of the calculation. 
If verified, the error seems not to be within the tool but either at the DWD or the ERC measurement station.

**Comment by MartinRaetz** [comment]
Here the raw hourly DWD data as a backup check:
```
15000;2023010909:42;    1;   -999;   17.0;   17.0;   0;    80.05;2023010910:00;eor
15000;2023010910:42;    1;   -999;   22.0;   22.0;   0;    75.56;2023010911:00;eor
15000;2023010911:42;    1;   -999;   30.0;   31.0;   0;    73.20;2023010912:00;eor
```
4th column is the DiffHorRad in J/m2. Resulting in roughly 22 J/cm2 for that hour. Resulting in 61.11 Wh/m2.
Being roughly in line with the above-shown values.

**Comment by MartinRaetz** [comment]
@Jun-Jiang-92 
This should be easy to track!

Once you have installed AixWeather, you can run the example.
Then you can track the made changes through "import", "transformation to core data", "core data", "transformation to .mos", "mos".

But I think the problem is most likely somewhere between "import" and "core data".

**Comment by MartinRaetz** [comment]
I have gone through this and found that the summing from 10 min to hourly data does not work as intended. 

This is done here:
aixweather/transformation_to_core_data/DWD.py:150

I propose the following fix: 

```
    # resample some via sum some via mean -> results in average of following hour
    df_10min = df
    df = df.resample("H").mean()  # fills nan only if all nan in interval
    for var in variables_to_sum_DWD_historical:
        if var in df.columns:
            df_sum = (
                df_10min[var].resample("H").sum(min_count=1)
            )  # fills nan only if 1 value in interval
            df[var] = df_sum
```

**Comment by MartinRaetz** [comment]
@Jun-Jiang-92, what's the status here? Let me know, if I can help you!

**Comment by Jun-Jiang-92** [comment]
@MartinRaetz I suppose the bug is caused by the incorrect resample of the df. See the code below:
https://github.com/RWTH-EBC/AixWeather/blob/daf3a8589bb89da5a6d28eccd2fff0d15bada4de/aixweather/transformation_to_core_data/DWD.py#L150C1-L157C29
```
    # resample some via sum some via mean -> results in average of following hour
    df = df.resample("H").mean()  # fills nan only if all nan in interval
    for var in variables_to_sum_DWD_historical:
        if var in df.columns:
            df_sum = (
                df[var].resample("H").sum(min_count=1)
            )  # fills nan only if 1 value in interval
            df[var] = df_sum
```
The df is already resampled by hour before calculating the sum of the radiation data. I will restructure the data processing here.

**Comment by MartinRaetz** [comment]
> I have gone through this and found that the resampling with summing up from 10 min to hourly data does not work as intended.
> 
> This is done here: aixweather/transformation_to_core_data/DWD.py:150 https://github.com/RWTH-EBC/AixWeather/blob/daf3a8589bb89da5a6d28eccd2fff0d15bada4de/aixweather/transformation_to_core_data/DWD.py#L150C1-L157C29
> 
> I propose the following fix:
> 
> ```
>     # resample some via sum some via mean -> results in average of following hour
>     df_10min = df
>     df = df.resample("H").mean()  # fills nan only if all nan in interval
>     for var in variables_to_sum_DWD_historical:
>         if var in df.columns:
>             df_sum = (
>                 df_10min[var].resample("H").sum(min_count=1)
>             )  # fills nan only if 1 value in interval
>             df[var] = df_sum
> ```
> 
> First of all, thank you for finding this bug! @Jun-Jiang-92 In order to spread the knowledge about this Tool, I would like to ask you to implement the fix. I have created a branch related to this issue, which you can checkout. After applying the changes, you will also need to adapt the "unit test" files, as the new "correct" will change. I may help you with this. Just contact me 👍

Yes correct, this is what I already mentioned here.

**Comment by Jun-Jiang-92** [comment]
New comparison between the weather data from AC-Orsbach and EBC:
Day 0-90:
![grafik](https://github.com/RWTH-EBC/AixWeather/assets/59657205/600a0085-188b-41c6-b8cd-95aadc33faad)
Day 140-160:
![grafik](https://github.com/RWTH-EBC/AixWeather/assets/59657205/17032496-dd38-444c-b7a6-4d1938c9600f)

- Now, all solar radiation values (HDirNor, HDifHor and HGloHor) from both weather stations are comparable.
- All the other values keep unchanged. (Except winSpe and winDir: It seems that both default values were set to 0 by other commits, if there is no data from DWD available.)

@MartinRaetz Thank you for your help!
