### ISSUE TITLE
Timezone shift in the opposite direction

### ISSUE THREAD

**Issue by TobiasSpratte** [RWTH-EBC/AixWeather#46]
**Describe the bug**
A time zone shift in the wrong (opposite) direction occurs, when importing an epw file with a time zone unequal to zero and exporting it to epw or another format with time zone zero.

**To Reproduce**
1. Import an epw file with timezone unequal to zero
2. Export to mos / epw / csv / ... wih timezone zero
3. Compare exported and imported files.

**Expected behavior**
Importing an epw file with timezone UTC+1 and exporting it with UTC0 should result in a time shift of -1, e.g. the value at 03:00 in the input file should be at 02:00 in the output file. 

**Screenshots**
Input File left (epw) and output file right (epw)
![image](https://github.com/RWTH-EBC/AixWeather/assets/135248974/cf588619-062f-4832-93cc-cad040fba946)

**Comment by MartinRaetz** [comment]
Thank you finding this:
You would have to save the original time zone in the metadata and call it up again later when converting to the output format, because the core format should always remain utc (from my point of view)

**Comment by MartinRaetz** [comment]
Could you please also check, whether the behaviour with a TRY import (TRY is in MEZ) is correct? i have checked the code, I think I can exclude the other import options.

**Comment by MartinRaetz** [comment]
- [ ] check whether bugfix only applies desired changes
- [ ] update test files

**Comment by TobiasSpratte** [comment]
The behaviour with a TRY import was already correct. It only affected the epw import.
