### ISSUE TITLE
Missing requirement shapely

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/AixWeather#52]
**Describe the bug**
`shapely` is used in `TRY` but not in the setup.üy

**Comment by MartinRaetz** [comment]
It seems to be installed automatically with the stated packages, as the CI tests pass. 
Though, if loading it directly, it is probably best practice to install it explicitly?

**Comment by DaJansenGit** [comment]
same issue for me. Installed via `pip install AixWeather` and `shapely` is missing as module
