### ISSUE TITLE
Weather File Converting Error: Request Entity Too Large

### ISSUE THREAD

**Issue by tosch4** [RWTH-EBC/AixWeather#64]
After choosing an *.epw File and selecting *.mos as output format, i tried to format the weather files by clicking on download. The online app sends me to an error page with the title "Request entity too large".

![grafik](https://github.com/user-attachments/assets/388b2134-f18b-474d-bb35-a2d1ded50d02)

**Comment by MartinRaetz** [comment]
Hey @tosch4, 
thanks for raising the issue and informing the VM-Admins. 
I got mail that they have changed a setting and you may try again!

Let them know if its fixed! :)

**Comment by tosch4** [comment]
VM settings are changed by @Marvin Kluge. Issue is fixed. Thank you for your support!
