### ISSUE TITLE
[JOSS Review] OSI conform license

### ISSUE THREAD

**Issue by FlorianK13** [RWTH-EBC/AixWeather#67]
This comment is part of https://github.com/openjournals/joss-reviews/issues/7344

Your [license](https://github.com/RWTH-EBC/AixWeather/blob/main/LICENSE) has an added paragraph and hence is not the BSD license anymore. Hence I cannot really check the field of OSI approved licenses in my review checklist. 

Is there a reason to have this modification to your license?

**Comment by MartinRaetz** [comment]
@FlorianK13, thank you for the Issue! 

I have already updated the license in the [Joss paper branch](https://github.com/RWTH-EBC/AixWeather/tree/4-joss_paper). 
My original plan was to merge it to the main branch in one "Joss-PR" once everything is approved. Though, if required I can also make the changes now?

**Comment by FlorianK13** [comment]
Ah great, I didn't see that. Of course you can merge it afterwards as well, I don't mind.
