### ISSUE TITLE
[JOSS Review] Invalid DOI formatting

### ISSUE THREAD

**Issue by FlorianK13** [RWTH-EBC/AixWeather#68]
This comment is part of https://github.com/openjournals/joss-reviews/issues/7344

Just a small issue: The editorial bot found this doi with wrong formatting:

❌ INVALID DOIs

- https://doi.org/10.1016/S0378-7788(00)00114-6 is INVALID because of 'https://doi.org/' prefix

**Comment by MartinRaetz** [comment]
Thank you, @FlorianK13.

I have deleted the prefix in commit 18ca6c0ffe78047d6084cbb466592168fee27357.

I do think this will solve the issue. If not, please feel free to reopen.
